
FROM mcr.microsoft.com/azure-functions/python:4-python3.11


RUN apt-get update && \
    apt-get install -y curl && \
    apt-get update && \
    apt-get install -y azure-functions-core-tools-4 && \
    curl -sL https://aka.ms/InstallAzureCLIDeb | bash

ENV AzureFunctionsJobHost__Logging__Console__IsEnabled=true

# Step 2: Create a new Azure Functions project
#RUN func init MyFunctionApp --python

# Step 3: Navigate into the project directory
#RUN cd MyFunctionApp

# Step 4: Create a new HTTP-triggered function
#RUN func new --template "HTTP trigger" --name MyHttpTrigger

# Step 5: Run the function locally
CMD  ["/bin/bash"]