
FROM mcr.microsoft.com/azure-functions/python:4-python3.11


RUN apt-get update && \
    apt-get install -y curl && \
    apt-get update && \
    apt-get install -y azure-functions-core-tools-4 && \
    curl -sL https://aka.ms/InstallAzureCLIDeb | bash

ENV AzureFunctionsJobHost__Logging__Console__IsEnabled=true

# Import as otherwise point to wrong directory and function app will not be found
ENV AzureWebJobsScriptRoot=""


# Step 5: Run the function locally
CMD  ["/bin/bash"]